### PR TITLE
Feature/readme

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
add new feature to use print actual help from program to readme text.

just run following command: 

`python -m cogapp -d ./README.rst.tmpl > ./README.rst`

this require `cogapp` which can be installed with `pip install cogapp`

### CODE REVIEW

**Comment by 0xl3vi** [comment]
Nice! I will take a look on this later.

Let's keep the original README.rst,
and create a script to generate the README.rst in the tools/ folder?

**Comment by rachmadaniHaryono** [comment]
i have move it to tools folder, but the template is not up to date to your recent commit for readme, where you remove the option section. 

you can put the cogapp bracket on where you want the option section should be and generate the readme the same way like my comment about. just modify the output readme file.

**Comment by 0xl3vi** [comment]
Hi @rachmadaniHaryono.
I thought you will write a python script like "gen_readme.py" not a template.
you can re-pull the changes from your README.rst to README.rst (master).
but not the template.

sorry for that.

**Comment by rachmadaniHaryono** [comment]
>I thought you will write a python script like "gen_readme.py" not a template.

writing python script only will make it unreadable. this template can still be seen with rst viewer and dev can still edit it as rst not as python script.

here is my second attempt to generate the readme, 

the actual command now is `python -m cogapp -d ./tools/README.rst.tmpl > ./README.rst`

**Comment by 0xl3vi** [comment]
@rachmadaniHaryono LGTM, I maybe will rename tools.
Thank you.

**Pull request merged**
