### PR TITLE
chg: dev: add __main__

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
with this program can be run with `python -m we_get`

### CODE REVIEW

**Comment by 0xl3vi** [comment]
Hi @rachmadaniHaryono thank you very much for your contribution.
but why we will need to run we-get in this way?

**Comment by rachmadaniHaryono** [comment]
it is another entry point use mostly by module. most module use it and when the program is zipped, it can also run from them. 

related SO
- http://stackoverflow.com/questions/31327762/what-is-the-difference-between-init-py-and-main-py
- http://stackoverflow.com/questions/4042905/what-is-main-py

**Comment by 0xl3vi** [comment]
@rachmadaniHaryono yes I know but we-get is not a library.
Most of the users will not call we-get from python -m <X>.
they will run we-get from the terminal.

In the future I will add API for we-get

**Comment by rachmadaniHaryono** [comment]
>we-get is not a library

no it doesn't have to be library to have `__main__.py` file.

>Most of the users will not call we-get from python -m .

while this is true, it is only to add option for user to call it that way

>they will run we-get from the terminal.

it is also run on terminal (and not python interpreter)

but i will agree to this, so should i close this pr?

**Comment by 0xl3vi** [comment]
@rachmadaniHaryono let's keep it open for 1 week, maybe other users will want this.

**Comment by 0xl3vi** [comment]
Hi @rachmadaniHaryono I will merge this I tested we-get and this is a good addition to the project thank you :+1:

**Pull request merged**
