### PR TITLE
Format everything in accordance with PEP8

### PR DESCRIPTION
**Pull request by Hendrikto**
Before:
  $ pep8 . --count
  > ...
  > 557

After:
  $ pep8 . --count
  > ...
  > 1

There is one instance that I wasn't sure how to deal with:
  ./we_get/core/we_get.py:34:80: E501 line too long (90 > 79 characters)

### CODE REVIEW

**Comment by 0xl3vi** [comment]
Hi @Hendrikto thanks for that.
but PEP-8 tabs should be 4 spaces?
https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces

**Comment by Hendrikto** [comment]
Hi 0xl3vi,

Yeah, it does require indentation to be a multiple of four spaces. Here is
the error message: "E111 indentation is not a multiple of four"

Best regards,
Hendrikto

**Comment by 0xl3vi** [comment]
@Hendrikto what I meant is that your pull request is not with 4 spaces.

**Comment by Hendrikto** [comment]
@0xl3vi Well, pep8 thinks it is, just ran `pep8 --select=E111 .` to verify and it does not find errors.

**Comment by 0xl3vi** [comment]
@Hendrikto no when I ran `pep8 --select=E111 .` I get:

```
./we_get/core/we_get.py:125:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:127:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:129:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:132:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:133:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:134:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:136:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:142:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:144:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:146:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:148:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:151:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:153:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:155:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:159:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:160:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:161:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:164:3: E111 indentation is not a multiple of four
./we_get/core/we_get.py:165:3: E111 indentation is not a multiple of four
./we_get/core/we_get.py:170:3: E111 indentation is not a multiple of four
./we_get/core/we_get.py:176:7: E111 indentation is not a multiple of four
./we_get/core/we_get.py:179:3: E111 indentation is not a multiple of four
./we_get/core/we_get.py:184:7: E111 indentation is not a multiple of four
.....
.....
....
```

**Comment by Hendrikto** [comment]
@0xl3vi I can even point you to the specific line you named so you verify yourself: https://github.com/Hendrikto/we-get/blob/pep8/we_get/core/we_get.py#L125

Are you sure you are running this
1. on the correct repo
2. on the pep8 branch
?

**Comment by 0xl3vi** [comment]
@Hendrikto sorry I tested it again and it works.
but the tabs are not 4 spaces, we need to fix that before I wil merge.

**Comment by Hendrikto** [comment]
@0xl3vi Well I really do not know what to say. Tabs are four spaces. Have a look here https://github.com/Hendrikto/we-get/tree/pep8, go to any of the lines specified in your earlier comment and count the spaces.

How are you testing this? You need to be on the pep8 branch.

**Comment by 0xl3vi** [comment]
@Hendrikto I am testing this on VIM.
you can test it : insert 4 spaces in the source code and see if it matches the original tabs.

**Comment by Hendrikto** [comment]
@0xl3vi Okay, dude. I am tired of this. Take it or leave it. It is correct. I do not know what you're doing.

Go to some folder and run

    git clone https://github.com/Hendrikto/we-get.git
    cd we-get
    git checkout pep8
    pep8 --select=E111 .

You will not get any errors. I suspect you didn't do the checkout step or something.
[Proof](http://oi64.tinypic.com/292qxw0.jpg)

**Comment by 0xl3vi** [comment]
@Hendrikto 
Hi man I did the test. let's leave it.
I will merge and refactor this later.

Thanks for addressing my comments!
sorry but I need to closely pull requests :+1:

**Comment by Hendrikto** [comment]
@0xl3vi Thank for merging and no problem but I really cannot verify your problem.

Even after just pulling what you merged I still get no error: [Screenshot](http://oi68.tinypic.com/15840mp.jpg)

**Comment by 0xl3vi** [comment]
@Hendrikto when I started the project I used 2 spaces for indentation,
and it's still 2 spaces. why `pep8` thinks it's 4 I dont know :disappointed: 

* How I tested the tabs.
> In vim.

`pep8` also did not show me errors on the current branch :wink: 
sorry for the misunderstanding.

**Pull request merged**
